
# name = int(input("Enter ur name: "))
# college = int(input("Where do you study: "))
# city = int(input('city name: ')
Age = int(input("Enter ur age: "))
# animal = int(input("National animal of India: "))
# print(name, college, city, age, animal)
Age = int(Age) 
print(Age, type(Age))
a = int(input('Enter a number: '))
b = int(input('Enter a number: '))
print( a + b )